/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cs2263_hw02;

import javafx.application.Application;
import javafx.stage.Stage;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
